mod element;
mod big_element;
mod factory;
mod ops;
mod broadcast;
mod bigint;
mod big_field;
mod big_array;
mod array_kind;
mod cache;
mod normal;

pub use array_kind::GaloisArray;
pub use big_array::BigFieldArray;
pub use big_element::{BigFieldElement, GaloisElement};
pub use bigint::{field_order_big, needs_bigint, FieldValue};
pub use big_field::{field as galois_field, field_from_order, BigGaloisField, FieldKind, GF2};
pub use cache::{cached_big_field, cached_field, cached_field_from_order, clear_field_cache};
pub use element::{ElementRepr, FieldElement};
pub use factory::{GaloisField, GF};
pub use normal::{is_normal_element, normal_element};
pub use ops::FieldArray;
